Enumerate all and only downloaded subdirectories
Eddio0141/unitas_setup_tool pull request #64
Opened 2023-08-15 06:30 UTC by 8kat

This PR addresses item 2 of #58 by enumerating over every item in the source directory, allowing for the download contents to change significantly. There are a couple of design considerations here:

1. Should we only copy over subdirectories, or every entry in a directory? currently this PR does the latter. 
2. Should there be user-facing warnings if an expected subdirectory (e.g. plugins) is missing? What if there's a directory/file we normally wouldn't expect?

I also removed unitas_patchers_dir() since it was only used in source_dest_dirs.

2023-08-15 15:55 UTC, Eddio0141 commented
Yeah now I see how inconsistent my UniTAS project release directory structure is.

I'm thinking of changing this so the directory would reflect what would end up on the game's directory, so the zip would contain the `BepInEx` directory which could be directly copied, which I can apply to all releases of UniTAS.

On future UniTAS releases the content of what ends up in the game directory could change, but it shouldn't extend beyond the game directory.

Example of this change [UniTAS_BepInEx_v0.5.0.zip](https://github.com/Eddio0141/unitas_setup_tool/files/12345580/UniTAS_BepInEx_v0.5.0.zip)

As for the second problem, I don't have plans right now to have things checked, but there could be a hash check in some way to make sure things are downloaded properly and if the folder has been changed and handle that accordingly. Probably would be done in another pr if there's some idea to handling this.

2023-08-15 17:22 UTC, Eddio0141 requested changes
I've changed the UniTAS release to match the game's base directory.
Copying all content from inside the folder directly onto the game directory should work.

2023-08-16 05:43 UTC, 8kat commented
I just removed the following: 

```rust
let dest_dir = game_dir.join("BepInEx");
```
and replaced subsequent references to dest_dir with game_dir. 

Do we care about the fact with old versions of UniTAS the file structure wouldn't necessarily work? If it is then I think adding a versioning check to conditionally join BepInEx would be reasonable instead.

2023-08-16 16:39 UTC, Eddio0141 commented
No worries about that, I've updated all of the past release zips to match the current file structure.
As for the main branch and future releases, it will be following the same structure as well.

2023-08-17 23:38 UTC, 8kat commented
branch should have the changes in place now.

2023-08-18 05:03 UTC, Eddio0141 approved these changes
Looks good, thanks!

2023-08-18 05:04 UTC, merged